---
title: "Pathway analysis of pNF cell lines"
author: "Sara Gosline"
date: "June 14, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(synapser)
synLogin()

```

## Cell line info

First we get the pNF data
```{r Get Data, echo=FALSE}
rna.seq.data<-read.table(synapser::synGet('syn12333637')$path,header=T,sep='\t')
require(tidyverse)
rna.seq.data<-rna.seq.data%>%group_by(Gene,Sample)%>%summarize(geneTotals=sum(Value))%>%spread(key=Sample,value=geneTotals)
rna.seq.mat<-apply(as.matrix(dplyr::select(ungroup(rna.seq.data),-Gene)),2,as.numeric)
rownames(rna.seq.mat)<-rna.seq.data$Gene
rna.seq.mat<-apply(rna.seq.mat,2,function(x) (x-mean(x,na.rm=T))/sd(x,na.rm=T))



```
Then we get the CCLE and Sanger data
```{r get outside data}

ccle.data<-read.table(synapser::synGet('syn11902828')$path,header=T)
sanger.data<-read.table(synapser::synGet('syn10507638')$path,header=T,sep=',')
rownames(sanger.data)<-sanger.data$X
sanger.mat<-t(sanger.data[,-1])
sanger.mat<-apply(sanger.mat,2,function(x) (x-mean(x,na.rm=T))/sd(x,na.rm=T))

overlap<-intersect(intersect(rownames(rna.seq.mat),rownames(sanger.mat)),rownames(ccle.data))
combined.mat<-cbind(sanger.mat[overlap,],ccle.data[overlap,],rna.seq.mat[overlap,])
```


## Then we re-format and run ssGSEA


```{r GSVA calling, echo=FALSE}
require(GSVA)
load('../../data/geneSets.RData')

#create a gene set with only glutamine signatures
new.list<-c(geneSet.c2[grep('GLUTAMINE',names(geneSet.c2))],geneSet.pathway[grep("GLUTAMINE",names(geneSet.pathway))])#geneSet.c2[grep('METAB',names(geneSet.c2))],geneSet.pathway[grep("METAB",names(geneSet.pathway))])

g.res<-t(gsva(as.matrix(combined.mat),new.list,method='ssgsea',rnaseq=TRUE,verbose=FALSE))

gdf<-data.frame(g.res)

gdf$Sample<-rownames(g.res)

g.df<-gdf%>%gather(Pathway,Value,-Sample)%>%mutate(isPNF=sapply(Sample,function(x) ifelse(x%in%colnames(rna.seq.data),"NF",ifelse(x%in%colnames(sanger.mat),"Sanger","CCLE"))))



#library(pheatmap)
#pheatmap(t(g.res),show_rownames = F,annotation_row = data.frame(annotations),cellheight=10,cellwidth=10)

library(ggplot2)
ggplot(g.df)+geom_jitter(aes(y=Pathway,x=Value,col=isPNF))
```

Now we can see what the results are.
